--drop table if exists orders cascade;
--drop table if exists clients cascade;
--drop table if exists employees cascade;
--drop table if exists products cascade;

CREATE TABLE IF NOT EXISTS orders (
orderId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
clientId BIGINT NOT NULL,
employeeId BIGINT NOT NULL,
expectedTime TIMESTAMP WITHOUT TIME ZONE,
productId BIGINT NOT NULL,
productCost BIGINT NOT NULL,
status varchar(30),
timestamp TIMESTAMP WITHOUT TIME ZONE
);